### ISSUE TITLE
shorthand functions throwing error when passed an object

### ISSUE THREAD

**Issue by ornj** [wheresrhys/fetch-mock#113]
Since the shorthand methods are passing an object to the options argument on `mock`, both sides of the check on [line 137](https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js#L137) are truthy when you provide a response object causing the error to throw. 

This is with v5.0.0

**Comment by ornj** [comment]
```js
// Works
fetchMock.mock('http://foo.com', { foo: 'bar' })

// Error
fetchMock.get('http://foo.com', { foo: 'bar' })

// Also an Error
fetchMock.mock('http://foo.com', { foo: 'bar' }, { method: 'GET' })
```

**Comment by Anahkiasen** [comment]
Same thing here

**Comment by mehdichamouma** [comment]
Same error here.

As a workaround you can still use the one-argument signature: 

`
fetchMock.mock({
    matcher: 'http://foo.com',
    response: { foo: 'bar' },
    method: 'GET'
})
`

**Comment by mehdichamouma** [comment]
As @ornj said, the error is thrown because the conditions `if (options && /[A-Z]+/.test(response))`on line 137 are truthy.

In fact, you want to check if response is a HTTP Method, so you check if response is a string. But `/[A-Z]+/.test(obj)`, with `obj` a plain obj, return `true` - _I don't know why, if someone knows please tell me why_. 

So others solutions to check if the user want to use a V4 signature would be:

- check `typeof response === "string"`, but in v5.0.0 response could be a `string` and an error will be thrown.
- check if response is a HTTP method, but in the (rare) case where the user want to mock a call that return `get, post, ...` or other http methods, an error will be thrown.
- check `options && !options.method`but the method will be required.

Instead, we should simply remove this legacy check ?

**Comment by wheresrhys** [comment]
good spot. I'll add a failing test and release a fix as soon as I can. PRs to that effect welcome 🙊

**Comment by wheresrhys** [comment]
> /[A-Z]+/.test(obj), with obj a plain obj, return true - I don't know why, if someone knows please tell me why.

It's because `{}.toString` is something like `[object Object]`... which contains an upper case letter.

I should've used  /^[A-Z]+$/

**Comment by ornj** [comment]
Why the regex instead of just testing if the value is a string and in a list of HTTP methods?

**Comment by wheresrhys** [comment]
simple way to throw a helpful error most of the time it's needed with hopefully few false positives. 

It's not 100% foolproof, but I did say PRs welcome...

**Comment by ornj** [comment]
As time permits. Thank you for maintaining this project.

**Comment by mehdichamouma** [comment]
> It's because {}.toString is something like [object Object]... which contains an upper case letter.
>
> I should've used /^[A-Z]+$/

Thanks. :)
