### ISSUE TITLE
Unmatched calls where I don't expect them

### ISSUE THREAD

**Issue by emirotin** [wheresrhys/fetch-mock#136]
Hi and thanks for the great library.

I have troubles using it in one of the projects though and would appreciate some help.

So first let's look at the project that works _just fine_: https://github.com/emirotin/resin-request/tree/sdk-browser.
It's a relatively simple library, all the code is in `lib`. It wraps around `fetch` (which it expects to be present as global) and does the calls to a couple of specific API servers.
The tests are in `tests`. They're run with `mocha` in `node`, and with `karma`+`phantomjs`+`mocha` in the browser, and they work.
The tests use `isomorphic-fetch` and `fetch-mock`.
I've also verified (just in case) that the library actually works in the browser without mocking.

Now let's look at https://github.com/emirotin/resin-pine/tree/sdk-browser (you can git clone and `npm install`, all the deps are public, specific deps are loaded from github).
It's a tiny library, it wraps around the previous one and another library that does the request formatting and calls the previous library in the end. It literally does nothing about the network, just juggles the data.
This project has the same structure, doesn't import `isomorphic-fetch` (except in the tests), has the tests that have the identical setup.
The tests run fine in `node`. In the browser I see a bunch of `unmatched call` errors and the tests fail.

I would really appreciate any ideas what could go wrong.
The previous setup (`request` instead of `fetch`) passed the tests both in node and the browser, but it had specific issue when ran in the actual app.
Thanks in advance.

**Comment by wheresrhys** [comment]
This might help with #103 - there's an issue I've seen occasionally where the order of importing things breaks fetch-mock because fetch-mock may try to restore global fetch after some module has imported isomorphic-fetch, or something like that, but I've struggled to get a reduced test case. I'll see if I can do it with your code

**Comment by emirotin** [comment]
Thanks. But the thing is I understand the implications, so I first load the fetch polyfill, and then the rest of the requirements: https://github.com/emirotin/resin-pine/blob/sdk-browser/tests/pine.spec.coffee

**Comment by wheresrhys** [comment]
I'm guessing it's actually because the url you pass in to fetch-mock has a double slash in the browser: 'https://api.resin.io//whoami'. Which gives me an idea to re-add debug mode to log out what fetch-mock is being asked to do (supported in previous versions, but I removed it eventually as it was difficult to know if anyone found it useful)

**Comment by emirotin** [comment]
Woah, it's a good catch, let me check.

**Comment by emirotin** [comment]
That was it! Man, I've chased that for days...
One take-away: I should have closer look at what is the difference between the node and the browser envs.
Another one: would be great indeed if the lib reported "unmatched call to..., expecting..."
And yet another one: probably the lib need to be more flexible and normalize the URLs instead of treating them as literal strings.

But overall: thanks for your help, and this can be closed now.
