### ISSUE TITLE
fetch-mock, isormorphic-fetch, and nightwatch

### ISSUE THREAD

**Issue by marclar** [wheresrhys/fetch-mock#198]
Hi - I'm having trouble getting `fetchMock` to intercept any calls (and I did look at "`fetch` doesn’t seem to be getting mocked?" in the Troubleshooting docs.)

This sample works as expected:

```
var fetchMock = require('fetch-mock');

module.exports = {
  'random task': function (browser) {
    fetchMock.mock('http://rambo.was.ere', 301);
    fetch('http://rambo.was.ere')
      .then(res => {

        // SHOWS 1 CALL
        console.log('fetchMock.calls().matched.length:', fetchMock.calls().matched.length); 

        fetchMock.restore();
        browser.end();
      });
  }
};
```

This one doesn't:

```
var fetchMock = require('fetch-mock');

module.exports = {
  'Load the list page': function (browser) {
    fetchMock.mock('*', {hello: 'world'});

    browser.globals.login(browser)
      .click('.nw-publishers')
      .waitForElementPresent('ul.media-grid', 10000, function () {

        // SHOWS 0 CALLS
        console.log('fetchMock.calls().matched.length:', fetchMock.calls().matched.length); 

        fetchMock.restore();
      })
      .end();
  }
};
```

I'm guessing that example 1 works because I'm calling `fetch` from the test environment, whereas example 2 is trying to mock the `fetch` object in the browser environment (but failing to patch it).

My `index.js` is:

```
require('react-hot-loader/patch');

import Promise from 'bluebird';
window.Promise = Promise;
import 'isomorphic-fetch';
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import App from './App';

const render = Component =>
  ReactDOM.render(
    <App/>,
    document.getElementById('app')
  );

render(App);
```

I tried adding the browserified version of `fetch-mock` to my `index.ejs` but that prevents my page from loading at all (not sure why).

Any ideas about what I could try next?

Thank you...

**Comment by wheresrhys** [comment]
What you're trying to achieve is probably impossible with nightwatch (as far as my understanding of browser automation goes). Nightwatch is a browser automation tool, so the code you write for nightwatch operates _on_ the browser (via a limited set of APIs nightwatch provides to interact with the browser), rather than giving you full access to DOM, which is what fetch-mock relies on. It looks like your first example only works because it's running 100% in your nightwatch code, and doesn't have to interact with the browser. You could experiment with the `.injectScript()` method of nightwatch, but that feels like overly complicated setup

My advice would be to use a test runner such as karma for unit-testing as much of your code as possible. This loads your source code and test suite into a browser window so they both run in the same environment.

**Comment by marclar** [comment]
Thanks, @wheresrhys - I was able to get it working with script injection as you suggested (I can't get away from nightwatch at the moment).
