### ISSUE TITLE
Match url with query params event if the params are not in the same order

### ISSUE THREAD

**Issue by shmilky** [wheresrhys/fetch-mock#227]
Hi,
Would love it if the same matcher will handle both ```http://test.url?a=2&b=4``` and ```http://test.url?b=4&a=2```

**Comment by wheresrhys** [comment]
This has been requested before. I'm a bit reluctant to implement it. If you can suggest an API for this we can agree on and submit a PR then I will consider adding it.

**Comment by wheresrhys** [comment]
Have decided on the following API.

```js
fetchMock.mock('/url/without/qs', 200, {
  query: {
    field: 'value'
  }
});
```
This has the advantage of being compatible with any type of matcher

**Comment by wheresrhys** [comment]
Done in v6

**Comment by rajatvijay** [comment]
I see this was closed way back but seems like error logging can be improved. If the matching fails just because of the query params, some hint in the error logs can save a lot of time for devs

**Comment by wheresrhys** [comment]
I have a WIP fro implementing debug logging. It's not simple though because the same code is used for both matching fetch calls and for retrieving those calls later when inspecting - implementing debug logging in a way that makes it clear which of those phases the log is occurring during will require a bit of a refactor. I'm not sure exactly which approach to take yet
