### ISSUE TITLE
How can I mock authorized requests?

### ISSUE THREAD

**Issue by smellai** [wheresrhys/fetch-mock#290]
my actions use a method authenticatedFetch to load resources from protected API:

```
export default function authenticatedFetch(input, init) {
  let patchedInit = init;

  if (!init || typeof(init) !== 'object') {
    patchedInit = {};
  }

  return window.oauth.token().then(authToken => {

    const patchedHeaders = Object.assign(patchedInit.headers || {}, {
      'Authorization': `Bearer ${ authToken.token }`,
    });

    patchedInit = Object.assign(patchedInit, {
      headers: patchedHeaders,
    });

    return fetch(input, patchedInit);

  });
}
```

The test fails with "Cannot read property 'token' of undefined"

**Comment by wheresrhys** [comment]
This suggests to me that you are not retrieving the `authToken` object successfully from `window.oauth.token()`, so the problem is to do with that, not with the call to `fetch` that happens afterwards. Are you doing anything elsewhere in your code to mock `window.oauth.token()`? If not, try using something like [sinon](http://sinonjs.org/)
