### ISSUE TITLE
Proposal: Normalise all Requests to url + options pairs

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#311]
As raised in [this issue](https://github.com/wheresrhys/fetch-mock/issues/297), when fetch is called with a `Request` object then it is preserved as a Request object in all the internals of the library.

It seems - potentially - sensible to normalise every Request to a `[url, options]` pair as early as possible, simplifying the code base, making certain features I'd like to add easier to implement, and separating the library's API from superficial differences in how fetch is called.

Is anyone tied to the current implementation? Please comment below

**Comment by adam-nielsen** [comment]
What effect would this have for users of the library?  If I understand correctly, the change won't affect how `fetch()` is handled or how the mocks are set up, so there would appear to be no externally visible changes other than some additional functionality like allowing `URL` objects to be passed in as well.

Since there is already `normalizeRequest()` in `compile-route.js` which does part of this job, are you considering calling this function much earlier in the process instead?

Although I only have very limited experience with the library, it seems like this would have minimal impact for users but would make it much easier to handle different parameters to `fetch()`, so it sounds like a good idea to me.

**Comment by wheresrhys** [comment]
It has 2 effects:
- Currently if fetch is called with a `Request` object, but `calls(url)` is called with the url of that request object, then it will return an empty array. This change will successfully match the url and return a non-empty array. I very much doubt this change will affect anyone
- Currently `calls()` returns `[[Request, undefined]]` if fetch is called once with a `Request`. This chaneg will mean it will return `[[url, syntheticOptions, Request]]`, where syntheticOptions is an inferred options object intended to replicate what would've been passed into the Request constructor (likely to be imperfect - will investigate as I try to implement)

**Comment by wheresrhys** [comment]
Fixed by https://github.com/wheresrhys/fetch-mock/pull/334
