### ISSUE TITLE
node-fetch is required by fetch-mock for Node.js, but not listed as a dependency

### ISSUE THREAD

**Issue by ajm13** [wheresrhys/fetch-mock#356]
First off, great work on this package, it is really nice!

**Problem:**
I am currently using `fetch-mock` for testing a Node.js application, and my application uses `isomorphic-fetch` for a global fetch.

When running tests locally, everything works (presumably because I have `node-fetch` installed globally), but when running through a continuous integration service like CircleCI, it fails saying it can't find the module `node-fetch` required by `fetch-mock` in `fetch-mock/src/server.js`

**Suggested fix:**
Add `node-fetch` as a dependency in `package.json`, instead of just a devDependency

**Comment by wheresrhys** [comment]
This is deliberate (it's documented, but perhaps not very clearly). The reason is to allow fetch-mock to be used with any version of node-fetch. I'm not entirely sure how you have fetch missing in CI though. If it's installed in your project's package.json, and CI runs `npm install` then it should be there in CI too. 

Thanks for the compliment 😄

**Comment by ajm13** [comment]
The problem seems to be that I am using `isomorphic-fetch` in my application, instead of `node-fetch`. So `node-fetch` isn't in my project's `package.json`, and thus CircleCI doesn't install it.

I fixed it for my project by adding `node-fetch` as a devDependency, as the only case `node-fetch` is needed is for `fetch-mock`'s `/src/server.js`.

**Comment by wheresrhys** [comment]
but node-fetch _is_ a dependency of isomorphic-fetch, so it should be there, so something weird is going on. Anyway, glad you solved it
