### ISSUE TITLE
response.sendAsJson = true overwrites response.status with fetch-mock 7.x

### ISSUE THREAD

**Issue by jharris4** [wheresrhys/fetch-mock#397]
I have the following test:

```
it('should reject if the fetch response has a bad status code', function() {
      let url = '/foo';
      let status = 500;

      fetchMock.mock({
        matcher: url,
        response: {
          status: status,
          headers: {
            ['Content-Type']: 'application/json'
          },
          body: '',
          sendAsJson: true
        }
      });

      return performFetch(fetch, url, {}, function(data) { return Promise.resolve(data); }).then(
        data => {
          fetchMock.restore();
          return Promise.reject('unexpected success');
        },
        error => {
          expect(error).toInclude('' + status);

          fetchMock.restore();
          return Promise.resolve('successful test');
        });
    });
```

This test passed successfully with version 6.x of `fetch-mock`, but fails with version 7.x.

I added some debug code to my `performFetch` function, and I can see with version 7.x that `response.status === 200` despite it being set to `500`.

Removing the `sendAsJson: true` does fix the problem, so it looks like there's a bug with `sendAsJson` that's specific to 7.x.

**Comment by wheresrhys** [comment]
Thanks for the detailed report. I'll look into it sometime during the next few days

**Comment by wheresrhys** [comment]
I think I see what you're doing wrong. Can you try the following please
```
      fetchMock.mock(url, {
          status: status,
          headers: {
            ['Content-Type']: 'application/json'
          },
          body: ''
      }, {
          sendAsJson: true
      });
```
In v7 sendAsJson and some other options have [moved off the second parameter of `.mock()`, to the third](https://github.com/wheresrhys/fetch-mock/blob/master/docs/v6-v7-upgrade-guide.md#sendasjson-and-includecontentlength-options-have-moved)

I recommend moving to using fetch-mock using 3 parameters rather than a single config object; since about v3 the documentation has been written with this pattern in mind - the only reason I still support the single object pattern is because, internally, that's what fetch-mock uses, so it's no extra work to support it.

I will add a more informative warning to aid people's migration to v7

**Comment by jharris4** [comment]
Finally looking at this again. It's a bit of a stretch to say I'm doing something wrong if you changed the API and it worked prior to your change... ;-)

Also, the sample code you provided doesn't show how to set the response code, which was kind of the whole point of the test case I shared!

Can you offer any further advice? Thanks.

**Comment by jharris4** [comment]
Hi, thanks for reopening, in the end, my solution was to just remove `sendAsJson: true` from all the options to fetchMock in all of the tests and that more or less did the trick.

I guess the main feedback I'd have would be that it would be good to draw people's attention to the fact that the way `sendAsJson` option works changed between version 6.x and 7.x

**Comment by wheresrhys** [comment]
It's in the upgrade guide https://github.com/wheresrhys/fetch-mock/blob/master/docs/v6-v7-upgrade-guide.md#sendasjson-and-includecontentlength-options-have-moved
