### ISSUE TITLE
Error: TypeError: Cannot read property 'prototype' of undefined when using on nodejs

### ISSUE THREAD

**Issue by cesarjr** [wheresrhys/fetch-mock#407]
Hi guys!

I'm almost sure it's my mistake, but I spent one entire day trying to solve and I've being failed 😞.

I'm trying to configure the fetch-mock on node to use with jest. I tried a lot of things and the best result that I have is this:

![image](https://user-images.githubusercontent.com/824198/50566568-7b49e400-0d22-11e9-884f-89720899de3a.png)

I'm sure my mock is working because if I pass it through parameter to the "Myclass.query" it works perfectly.

I'm also sure that the mock is arriving in my test file, because the mock function is present in the fetch module.

But... all together aren't working 😭.

I create a very simple and small project to see this problem happening:

https://github.com/cesarjr/test-node-fetch

Can anyone help me?

**Comment by wheresrhys** [comment]
Ooooh, this is an interesting case.

I _think_ that because you are setting a global mock for `node-fetch`, then when `fetch-mock` requires `node-fetch` internally (in order to use e.g. the `Request` constructor), the mock is applied here too, so `fetch-mock` is unable to access anything in the `node-fetch` module. I'm not sure what the idiomatic jest way would be to work around this, other than to explicitly declare the mock in each test suite rather than relying on the `__mocks__` directory convention.

I advise raising an issue with jest (or maybe there's a jest community site?). Please can you also reply here to let me know of any solution(s) you're given. I will definitely need to update the docs here to expand on the advice I currently give for use with jest

**Comment by cesarjr** [comment]
Hi! @wheresrhys! If I declare the mock in each test suite, I have a different problem!

If I do this locally, the fetch in my implementation is not mocked. In other words, I think the line `nodeFetch.default = fetchMock;` in your example does not work.

![image](https://user-images.githubusercontent.com/824198/50578009-d232e480-0e1a-11e9-9a0c-28626e1e380a.png)

Actually, this was my first try 😞

I created here another branch with the implementation as you recommended:

https://github.com/cesarjr/test-node-fetch/pull/1/files

Could you try to help me again? Unfortunately I'm not able to find a solution for my problem.

Thank you!

**Comment by wheresrhys** [comment]
Sorry for the slow response.

The way I suggested in the docs works if you're transpiling your server side code using babel, because `nodeFetch.default` gets used as the main `export`. But does not work if you're just using the files 'straight'... which is obviously the main use case. I've raised an issue https://stackoverflow.com/questions/54065941/how-to-mock-in-jest-using-an-implementation-which-has-the-original-implementat to ask for advice

**Comment by cesarjr** [comment]
Hi @wheresrhys !

Someone answered to me at StackOverflow.

https://stackoverflow.com/questions/54000152/jest-with-fetch-mock-generating-error-typeerror-cannot-read-property-prototyp/54029024#54029024

I think the solution is not good enough, because it will force me to bypass the node injection system.

But he explain the reason of the problem.

**Comment by wheresrhys** [comment]
I finally cracked it @cesarjr 

## __mocks__/node-fetch.js
```js
const nodeFetch = jest.requireActual('node-fetch');
const fetchMock = require('fetch-mock').sandbox();
Object.assign(fetchMock.config, nodeFetch, {
	fetch: nodeFetch
});
module.exports = fetchMock;
```

**Comment by wheresrhys** [comment]
Thanks for raising the issue. I'm updating the docs now and will close this

**Comment by ashoksudani** [comment]
Nothing works for me.

I had to  fall back to

And it just worked out of the box.

```
"fetch-mock": "9.10.3",
"node-fetch": "2.6.0",
```

I have questions though if you can please answer:

- does node-fetch make `fetch` available as global variable by default or not?
Because apart from installing these two modules, I have  not wrote any other line of code to make it work.

Because in docs its mentioned
```
When node-fetch has been assigned to global in your Node.js process (a pattern sometimes used in isomorphic codebases)
```
But I have not done this though.

**Comment by aperaham** [comment]
I fell back to an earlier version as @ashoksudani suggested and that worked for me.

**Comment by tkvlnk** [comment]
same as for @ashoksudani @aperaham 
rolled back to node-fetch and now works fine

"fetch-mock": "9.11.0",
"node-fetch": "2.6.0",

**Comment by rudolfbyker** [comment]
Same here. `fetch-mock 9.11.0` with `node-fetch 3.2.0` makes tests fail with "TypeError: Cannot read property 'prototype' of undefined". Downgrading `node-fetch` to version `2.6.7` makes the tests pass. So it must be a breaking change in node-fetch from v2 to v3 that `fetch-mock` is not taking into account (yet?).

**Comment by yuikoito** [comment]
I used `node-fetch 3.3.0` and got same errors. I think we need to fix something for v3, otherwise we should use v2.
