### ISSUE TITLE
Error: TypeError: Cannot read property 'prototype' of undefined in static function

### ISSUE THREAD

**Issue by camd** [wheresrhys/fetch-mock#413]
I hit an error when trying to use ``fetch`` in a ``static`` function.  I got the same error as issue #407.  I apologize if this is a dup.  But this time it was in a static function of another class.

I was able to solve this by importing ``isomorphic-fetch`` in my ``test-setup.js`` file for ``Jest``:

    import 'isomorphic-fetch';

Credit for solution here: https://github.com/facebook/react-native/issues/11537#issuecomment-331235590

So, perhaps that's the solution, but I wanted to mention it here in case you're able to solve it a better way.

Here was my class:

    export default class JobModel {
        static getList(repoName, options, config) {
            const jobUri = 'http://example.com';

            return fetch(`${jobUri}${options ? createQueryParams(options) : ''}`).then(
                ...do stuff...

**Comment by edmorley** [comment]
We dug into this some more and it turns out it was due to us using the Jest option [browser: true](https://jestjs.io/docs/en/configuration#browser-boolean) (which we'd added to work around a bug with a different package). We're going to stop setting that Jest option and instead use a more narrowly scoped `moduleNameMapper` workaround for the other package's bug instead.
