### ISSUE TITLE
Query matching doesn't work for similar routes

### ISSUE THREAD

**Issue by sepo-one** [wheresrhys/fetch-mock#426]
This test is failing:
```javascript
it('overwriting similar routes with different queries', async () => {
  const localFm = fetchMock.createInstance();
  localFm.config.overwriteRoutes = true;

  localFm
    .mock('http://it.at.there/', 200, { query: { foo: '1' } })
    .mock('http://it.at.there/', 404, { query: { foo: '2' } })
    .catch();

  await localFm.fetchHandler('http://it.at.there/?foo=1');
  expect(localFm.calls(true).length).to.equal(1);

  await localFm.fetchHandler('http://it.at.there/?foo=2');
  expect(localFm.calls(true).length).to.equal(2);
});
```
The issue is similar to [this one](https://github.com/wheresrhys/fetch-mock/issues/422).
Guess route matching should also take query into account in `addRoute`.

**Comment by wheresrhys** [comment]
What happens if you have `localFm.config.overwriteRoutes = false`

And what's the output when the test fails?

**Comment by sepo-one** [comment]
Output is:
```javascript
 AssertionError: expected 0 to equal 1
      + expected - actual

      -0
      +1
```

When `localFm.config.overwriteRoutes = false` test passes.

But  the problem is when it's `true'.
Because those are different routes and should not overwrite each other.

**Comment by sepo-one** [comment]
Any update on this one ?

**Comment by wheresrhys** [comment]
I think this was basically a documentation problem, resolved in this commit https://github.com/wheresrhys/fetch-mock/commit/225f3ca402a662392735c67bdcf18a3b858e0724. Fixing this problem in code, so that any options are combined with the matcher to try to detect all clashes is hugely complex, and I do not want to open that can of worms. But the limitations, although implictly documented elsewhere, weren't really spelled out in the right place

Sorry it took so long
