### ISSUE TITLE
Params are missing in Request when fallbackToNetwork is enabled

### ISSUE THREAD

**Issue by cKiril** [wheresrhys/fetch-mock#438]
Version: 7.3.6

# Issue
When using `fetch-mock` with the `fallbackToNetwork` option set to `true` the fallback request is missing the body of the original `Request` object.

# Example
https://codesandbox.io/s/fetch-mockbugrequest-vzbcg

**Comment by wheresrhys** [comment]
Thanks for the thorough recreation info. Will be a while til I have time to look at fixing, but I have found the source of the bug if you fancy submitting a PR.

Essentially, it revolves around the fact that fetch-mock responses can be functions that return a Response. fetch is also a function that returns a Response, so fallbackToNetwork piggybacks on the function response behaviour, simply setting the response function to be fetch. This becomes problematic when executed because fetch-mock normalises any Request into a (url, options) pair, but this step doesn't extract `body` from the Request because that would lead to all sorts of complication elsewhere. So when this line runs https://github.com/wheresrhys/fetch-mock/blob/master/src/lib/fetch-handler.js#L18, the assumption is that `response` is a hand crafted function that expects a normalised Request, but in fact it's just `fetch`

Will get a fix out soon.

It's nice to get a bug report that's a genuine bug and not a compatibility issue for a change 😄

**Comment by wheresrhys** [comment]
fixed in 7.3.7

**Comment by cKiril** [comment]
Thank you for the quick fix 💯
