### ISSUE TITLE
es module distribution

### ISSUE THREAD

**Issue by LarsDenBakker** [wheresrhys/fetch-mock#446]
The code published to NPM is commonjs and a proprietary webpack bundle, both of which can't be run in the browser without transformations. 

Browsers use standard es modules as the module format. It would be great if `fetch-mock` can provide an es module distribution too so that it can be imported in the browser directly. As an example, sinon uses rollup to do this: (https://github.com/sinonjs/sinon). 

I'd be happy to create a PR for this if this is something you're interested in.

**Comment by wheresrhys** [comment]
Some notes on how this could be implemented https://2ality.com/2019/10/hybrid-npm-packages.html

**Comment by wheresrhys** [comment]
[v8.0.0-alpha.1](https://www.npmjs.com/package/fetch-mock/v/8.0.0-alpha.1) attempts to address this issue. Please leave a :+1: on the pull request https://github.com/wheresrhys/fetch-mock/pull/457 if your problem is solved, or alternatively leave a comment @LarsDenBakker @tomalec @sbryan @MathieuPuech
