### ISSUE TITLE
Support request body matching when using Ky

### ISSUE THREAD

**Issue by renanvalentin** [wheresrhys/fetch-mock#495]
Hello,

I'm using [ky](https://www.npmjs.com/package/ky) to make http requests and internally it uses Request object as a resource request.

This causes the body to be undefined breaking the following use case:

```javascript
  fetchMock.mock(
    "http://example.com/sample-1",
    {
      body: JSON.stringify({ foo: "bar" })
    },
    {
      body: {
        baz: "qux"
      },
      overwriteRoutes: true
    }
  );
```

The workaround for this was to use a matcher as a function and resolve the request:

```javascript
  fetchMock.mock(
    "http://example.com/sample-2",
    async (_, __, request) => {
      var { baz } = await request.json();
      if (baz === "qux") {
        return {
          foo: "bar"
        };
      }

      return undefined;
    },
    {
      overwriteRoutes: true
    }
  );
```

I've created this sample reproducing the issue:
[https://codesandbox.io/s/affectionate-snowflake-biv3s?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/affectionate-snowflake-biv3s?fontsize=14&hidenavigation=1&theme=dark)

Is this behavior expected? 

Thanks!

**Comment by wheresrhys** [comment]
Thanks for the report. I'll look into it

**Comment by wheresrhys** [comment]
This is quite easy to fix using node-fetch, but much harder in the browser. I woudl like to support ky though, so will work on a fix

**Comment by wheresrhys** [comment]
I don't think I can fix this without a breaking change. this is because extracting the body content from a Request instance can only be done asynchronously using a spec compliant Request instance. Therefore the step to normalise a Request into the object fetch-mock passes around internally (the first thing that happens on handling a request) must be made async. This in turn means that  the fetch handler cannot throw a synchronous error when something unexpected happens e.g. a call is made that has no corresponding mock.

It's unlikely that developers are relying on this behaviour other than when actively writing tests, but even so I think it'd be best to release as a major version. And even then I need to seriously weigh up what the best approach is:
- Always throw asynchronously, which is consistent, but may make debugging tests harder (or it might not... needs careful thought anyway)
- Refactor so that I don't need to throw asynchronously for most cases, but do for the body extraction case. This is probably a lot of work, will lead to a messier code base, and the inconsistency is likely to still confuse developers

Heres' the WIP PR https://github.com/wheresrhys/fetch-mock/pull/496/files

**Comment by wheresrhys** [comment]
Please leave a 👍 on the issue if you'd like this fixed

**Comment by renanvalentin** [comment]
Hey, sorry for the delay 👍

**Comment by wheresrhys** [comment]
Implemented in v9
