### ISSUE TITLE
Update node-fetch dependency to v3.x.x

### ISSUE THREAD

**Issue by akhmadullin** [wheresrhys/fetch-mock#620]
Hi.

node-fetch released new major version - 3.0.0

https://github.com/node-fetch/node-fetch/releases/tag/v3.0.0

Are you planning to update node-fetch dependency to ^3.x.x in fetch-mock?

**Comment by wheresrhys** [comment]
node-fetch@3 is ES modules only, so it would require updating this entire library from commonjs. Probably something I'll look at after addressing the ling backlog of other issues

**Comment by rainerbruemmer** [comment]
Hi @wheresrhys,

are there any news regarding node-fetch@3 compatibility?

**Comment by guillaumewuip** [comment]
Because of the `*` peerDependencies version field, users of `fetch-mock` can't see something is wrong when installing `node-fetch@3.x.x`: 

https://github.com/wheresrhys/fetch-mock/blob/1bdac54e1b482398cca0af9658a500de23e72367/package.json#L48-L50

Are you open to a PR updating the `node-fetch` peerDependencies version field  to be `< 3.0.0` for example? This could be released as a patch IMO.


```diff
   "peerDependencies": {
-    "node-fetch": "*"
+    "node-fetch": "< 3.0.0"
   },
```

**Comment by rudolfbyker** [comment]
Related: https://github.com/wheresrhys/fetch-mock/pull/625

**Comment by wheresrhys** [comment]
fetch-mock@10 is now out. It defaults to use native fetch, but you can also install node-fetch at any version and pass that in using the custom subclasses API https://www.wheresrhys.co.uk/fetch-mock/#usagecustom-classes
