### ISSUE TITLE
Mockery doesn't work as expected

### ISSUE THREAD

**Issue by timnew** [wheresrhys/fetch-mock#70]
I setup the `mockery` and `fetch-mock` as following code:

```js
import mockery from 'mockery'
import fetch from 'node-fetch'
import fetchMock from 'fetch-mock'
import MyModule from './MyModule'

fetchMock.useNonGlobalFetch(fetch)
// ...
    beforeEach(() => {
      mockery.enable({ useCleanCache: true })
      mockery.registerMock('node-fetch', fetchMock.mock(pattern, 'POST', 200).getMock())
    })

    afterEach(() => {
      mockery.deregisterMock('node-fetch')
      mockery.disable()
    })
```

And during the test, I found the request doesn't get mocked as expected, all request hit the real server and `fetchMock.called()` returns false

Did I missed something or what should I do?!?!

**Comment by wheresrhys** [comment]
You need to import `MyModule` after calling `mockery.registerMock`, which you can only do if using `require('./MyModule')`. I don't know if there are any other libraries that mock modules that deal with `import` better than mockery does. I doubt it though because they'd need to pretty closely coupled with babel

**Comment by timnew** [comment]
I realized the issue, and trying to figure out a solution. 
It is kind of painful while writing test for library rather than application.
I think the only way to solve the issue is to add another abstraction layer in the lib to enable developer to inject fetch ployfill into it.
Thanks for the help anyway

**Comment by Primajin** [comment]
I'm also having the Problem, that fetchMock does not actually mock away my request, and requests are running against real url.
I am using `import fetch from 'isomorphic-fetch';` in my react action.
I cant use mockery since it does not work with Webpack (https://github.com/mfncooper/mockery/issues/37). Do you have any different Idea?

**Comment by wheresrhys** [comment]
try `import  'isomorphic-fetch'` instead of `import fetch from 'isomorphic-fetch';`

**Comment by Primajin** [comment]
Great! I then first ran into #60 but with adding `require('isomorphic-fetch');` before my actual tests (e.g. `loadtests.js`) now everything runs smooth. You saved my day (and my code) Thanks!!

**Comment by shivasai09** [comment]
hi there, 
i am currently using fetch API to get the data from the server so i am using it like this
callApi.js
```
import fetch from 'isomorphic-fetch';
class CallApi {
static getInfo(){
fetch(url,body).then(res=>{res.json()})
}
}
export default CallApi
```
and in my  other file `book.js` i am using like this 
```
import CallApi from (./callApi.js)
...
.......
CallApi.then(res=>{do something})

```
it was working fine when i tried to unit test the `book.js` the fetch-mock was not mocking , so by referring this issue i have changed the way of importing
i have changed it go just 
`import 'isomorphic-fetch'`

all my unit test worked properly when i ran in the karma environment

But the problem is when i have started the application in localhost by running the command npm start
i am not able to fetch the data from the server due this small tweak which i have done it .. I am the error like this

```
10:2356 Uncaught Error: Cannot find module "imports?this=>global!exports?global.fetch!whatwg-fetch"
    at webpackMissingModule (10:2356)
    at eval (10:2356)
    at Object.<anonymous> (react.js:835)
    at __webpack_require__ (react.js:713)
    at fn (react.js:118)
    at Object.eval (NavigationComponent.js?b43f:5)
    at eval (828:414)
    at Object.828 (home.js:200)
    at __webpack_require__ (react.js:713)
    at fn (react.js:118)
```

but i revert the changes , which is importing the fetch like this 
`import fetch from ''isomorphic-fetch'`
my application ran perfectly but my test cases dint run .. because the` fetch-mock` library was unable to mock

what is the solution for this
