### ISSUE TITLE
Types broken in 10.x for ESM

### ISSUE THREAD

**Issue by wolfy1339** [wheresrhys/fetch-mock#779]
In between versions 10.0.8 and 10.1.0 there where some API removals that weren't backwards compatible

~~ie. the removal of the `sandbox()` method~~

~~This causes CI failures for in-range updates of fetch-mock

~~These changes were not listed in the changelog for the affected `fetch-mock` versions.~~
~~Could you revert the breaking change and simply deprecate the method?~~

~~I assume that this project respects semantic versioning.~~

EDIT: The JS methods were not removed, this is only a purely TS issue

**Comment by wheresrhys** [comment]
fetch-mock still has the `.sandbox()` method, even in v11 https://github.com/wheresrhys/fetch-mock/blob/main/packages/fetch-mock/src/lib/index.js..

Can you check is v11 works (it's identical expect from a fix to the built .cjs file)

**Comment by wolfy1339** [comment]
That is indeed odd. On my full ESM + TS setup the method is not working

error TS2339: Property 'sandbox' does not exist on type 'typeof import("/home/thomas/Desktop/Programming/probot/node_modules/fetch-mock/types/index")'.

**Comment by wolfy1339** [comment]
That is indeed odd. On my full ESM + TS setup the method is not working

error TS2339: Property 'sandbox' does not exist on type 'typeof import("node_modules/fetch-mock/types/index")'.

**Comment by wolfy1339** [comment]
Here is a minimal test case: https://github.com/wolfy1339/fetch-mock-typescript

**Comment by wheresrhys** [comment]
That is very weird. Do you think you could raise this on stackoverflow or some other typescript forum. Its' really unclear to me what the issue could be.

Playing around I found that setting the following in tsconfig.json works:

```
    "module": "esnext",
    "moduleResolution": "node",
```
but I don't really want to have to force users of fetch-mock to choose legacy settings in their project config

**Comment by wheresrhys** [comment]
Exploring more, it looks like the cause is the previous fix to address the commonjs use case https://github.com/wheresrhys/fetch-mock/issues/726:

> The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'.



If fetch-mock is globally set to `"type": "module"` and you use `import` in a `.ts` file in a project with `"type": "commonjs"` it converts the import to a require, but fails to use any of the export definitions in fetch-mock/package.json to see that fetch-mock is available as commonjs. For reasons I don't understand, this is not an issue when the user actually writes `require('fetch-mock')` in a .ts file.

However, if fetch-mock is *not* globally set to `"type": "module"` and you use `import` in a `.mts` file ( or`.ts` file in a project with `"type": "module"`) it fails to retrieve the types correctly.

The second situation feels worse and more confusing, and it feels right to have fetch-mock set to `"type": "module"` globally, so I think the way forward is to try to find an alternative solution to the original error from the other week.

**Comment by wheresrhys** [comment]
I think I now have a fix. To avoid me having to override my build steps (which doesn't deal with beta releases very well) I'd appreciate it if you could
1. check out #780 locally
2. `npm run build`
3. copy the fetch-mock package into your full project
4. let me know if it works

**Comment by wolfy1339** [comment]
Sorry for the late response,

That does seem to fix the issue
